export const nowPlaying = [
  
  {"adult":false,"backdrop_path":"/srYya1ZlI97Au4jUYAktDe3avyA.jpg","genre_ids":[14,28,12],"id":464052,"original_language":"en","original_title":"Wonder Woman 1984","overview":"Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s and finds a formidable foe by the name of the Cheetah.","popularity":3663.168,"poster_path":"/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg","release_date":"2020-12-18","title":"Wonder Woman 1984","video":false,"vote_average":7.2,"vote_count":2727},
  
  {"adult":false,"backdrop_path":"/dueiWzWc81UAgnbDAyH4Gjqnh4n.jpg","genre_ids":[18,878],"id":614911,"original_language":"en","original_title":"The Midnight Sky","overview":"A lone scientist in the Arctic races to contact a crew of astronauts returning home to a mysterious global catastrophe.","popularity":1309.808,"poster_path":"/51JxCk77ZCqLzbLkrDl9Qho6KUh.jpg","release_date":"2020-12-11","title":"The Midnight Sky","video":false,"vote_average":5.9,"vote_count":915},
  
  {"adult":false,"backdrop_path":"/cjaOSjsjV6cl3uXdJqimktT880L.jpg","genre_ids":[12,14,10751,16],"id":529203,"original_language":"en","original_title":"The Croods: A New Age","overview":"Searching for a safer habitat, the prehistoric Crood family discovers an idyllic, walled-in paradise that meets all of its needs. Unfortunately, they must also learn to live with the Bettermans -- a family that's a couple of steps above the Croods on the evolutionary ladder. As tensions between the new neighbors start to rise, a new threat soon propels both clans on an epic adventure that forces them to embrace their differences, draw strength from one another, and survive together.","popularity":1266.684,"poster_path":"/tK1zy5BsCt1J4OzoDicXmr0UTFH.jpg","release_date":"2020-12-10","title":"The Croods: A New Age","video":false,"vote_average":7.7,"vote_count":1142},
  
  {"adult":false,"backdrop_path":"/izNpxVcjKbF9BiYF4GVqxCOfewL.jpg","genre_ids":[18],"id":641662,"original_language":"en","original_title":"Pieces of a Woman","overview":"When a young mother's home birth ends in unfathomable tragedy, she begins a year-long odyssey of mourning that fractures relationships with loved ones in this deeply personal story of a woman learning to live alongside her loss.","popularity":546.408,"poster_path":"/OgUfLlhfBFx5BPK6LzBWFvBW1w.jpg","release_date":"2021-01-01","title":"Pieces of a Woman","video":false,"vote_average":7.1,"vote_count":239},
  
  {"adult":false,"backdrop_path":"/tGxKtDoIPqWM4XYjHutqH2hn5ca.jpg","genre_ids":[18,10749],"id":628333,"original_language":"en","original_title":"Wild Mountain Thyme","overview":"Headstrong farmer Rosemary Muldoon has her heart set on winning her neighbour Anthony Reilly's love. The problem is, Anthony seems to have inherited a family curse, and remains oblivious to his beautiful admirer. Stung by his father's plans to sell the family farm to his American nephew, Anthony is jolted into pursuing his dreams.","popularity":147.265,"poster_path":"/vMW81htT6Kki8x0G4UNb7l48iIr.jpg","release_date":"2021-01-08","title":"Wild Mountain Thyme","video":false,"vote_average":5.8,"vote_count":17},
  
  {"adult":false,"backdrop_path":null,"genre_ids":[],"id":784989,"original_language":"en","original_title":"Paranoid Thoughts","overview":"Paranoid Thoughts Race Through My Head","popularity":6.398,"poster_path":null,"release_date":"2021-01-13","title":"Paranoid Thoughts","video":false,"vote_average":0,"vote_count":0},
  
  {"adult":false,"backdrop_path":null,"genre_ids":[],"id":784776,"original_language":"en","original_title":"More And More","overview":"No Plot, No Meaning, No Point","popularity":4.037,"poster_path":null,"release_date":"2021-01-11","title":"More And More","video":false,"vote_average":0,"vote_count":0},
  
  {"adult":false,"backdrop_path":null,"genre_ids":[],"id":784077,"original_language":"en","original_title":"If I Had You","overview":"A Man Lies In Bed","popularity":2.731,"poster_path":null,"release_date":"2021-01-08","title":"If I Had You","video":false,"vote_average":0,"vote_count":0}

];