export const upcoming = [
  
    {"adult":false,"backdrop_path":"/srYya1ZlI97Au4jUYAktDe3avyA.jpg","genre_ids":[14,28,12],"id":464052,"original_language":"en","original_title":"Wonder Woman 1984","overview":"Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s and finds a formidable foe by the name of the Cheetah.","popularity":3663.168,"poster_path":"/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg","release_date":"2020-12-16","title":"Wonder Woman 1984","video":false,"vote_average":7.2,"vote_count":2727},
    
    {"adult":false,"backdrop_path":"/kf456ZqeC45XTvo6W9pW5clYKfQ.jpg","genre_ids":[16,35,18,10402,14],"id":508442,"original_language":"en","original_title":"Soul","overview":"Joe Gardner is a middle school teacher with a love for jazz music. After a successful gig at the Half Note Club, he suddenly gets into an accident that separates his soul from his body and is transported to the You Seminar, a center in which souls develop and gain passions before being transported to a newborn child. Joe must enlist help from the other souls-in-training, like 22, a soul who has spent eons in the You Seminar, in order to get back to Earth.","popularity":2925.462,"poster_path":"/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg","release_date":"2020-12-25","title":"Soul","video":false,"vote_average":8.3,"vote_count":3622},
    
    {"adult":false,"backdrop_path":"/aHYUj0hICtWZ5tPiCIm6pWUcjYK.jpg","genre_ids":[28,18,27,10752],"id":675327,"original_language":"en","original_title":"Shadow in the Cloud","overview":"A WWII pilot traveling with top secret documents on a B-17 Flying Fortress encounters an evil presence on board the flight.","popularity":2896.978,"poster_path":"/t7EUMSlfUN3jUSZUJOLURAzJzZs.jpg","release_date":"2020-12-31","title":"Shadow in the Cloud","video":false,"vote_average":6.1,"vote_count":138},
    
    {"adult":false,"backdrop_path":"/cjaOSjsjV6cl3uXdJqimktT880L.jpg","genre_ids":[12,14,10751,16],"id":529203,"original_language":"en","original_title":"The Croods: A New Age","overview":"Searching for a safer habitat, the prehistoric Crood family discovers an idyllic, walled-in paradise that meets all of its needs. Unfortunately, they must also learn to live with the Bettermans -- a family that's a couple of steps above the Croods on the evolutionary ladder. As tensions between the new neighbors start to rise, a new threat soon propels both clans on an epic adventure that forces them to embrace their differences, draw strength from one another, and survive together.","popularity":1266.684,"poster_path":"/tK1zy5BsCt1J4OzoDicXmr0UTFH.jpg","release_date":"2020-11-25","title":"The Croods: A New Age","video":false,"vote_average":7.7,"vote_count":1142},
    
    {"adult":false,"backdrop_path":"/nz8xWrTKZzA5A7FgxaM4kfAoO1W.jpg","genre_ids":[28,878],"id":651571,"original_language":"en","original_title":"Breach","overview":"A hardened mechanic must stay awake and maintain an interstellar ark fleeing the dying planet Earth with a few thousand lucky souls on board... the last of humanity. Unfortunately, humans are not the only passengers. A shapeshifting alien creature has taken residence, its only goal is to kill as many people as possible. The crew must think quickly to stop this menace before it destroys mankind.","popularity":1386.865,"poster_path":"/13B6onhL6FzSN2KaNeQeMML05pS.jpg","release_date":"2020-12-17","title":"Breach","video":false,"vote_average":4.1,"vote_count":48},
    
    {"adult":false,"backdrop_path":"/8rIoyM6zYXJNjzGseT3MRusMPWl.jpg","genre_ids":[14,10751,12,35,27],"id":531219,"original_language":"en","original_title":"Roald Dahl's The Witches","overview":"In late 1967, a young orphaned boy goes to live with his loving grandma in the rural Alabama town of Demopolis. As the boy and his grandmother encounter some deceptively glamorous but thoroughly diabolical witches, she wisely whisks him away to a seaside resort. Regrettably, they arrive at precisely the same time that the world's Grand High Witch has gathered.","popularity":470.418,"poster_path":"/b1C0FuXp4wiPmHLVKq4kwtDMgK6.jpg","release_date":"2020-10-25","title":"Roald Dahl's The Witches","video":false,"vote_average":6.8,"vote_count":1137},
    
    {"adult":false,"backdrop_path":"/iZ6wYtPGO6Hg4yP7O1ZXpITcx7V.jpg","genre_ids":[28,35],"id":682377,"original_language":"en","original_title":"Chick Fight","overview":"When Anna Wyncomb is introduced to an an underground, all-female fight club in order to turn the mess of her life around, she discovers she is much more personally connected to the history of the club than she could ever imagine.","popularity":362.813,"poster_path":"/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg","release_date":"2021-02-04","title":"Chick Fight","video":false,"vote_average":0,"vote_count":0},
    
    {"adult":false,"backdrop_path":"/eShw0LB5CkoEfYtpUcXPD85oz5Q.jpg","genre_ids":[27,53,35,14],"id":551804,"original_language":"en","original_title":"Freaky","overview":"A mystical, ancient dagger causes a notorious serial killer to magically switch bodies with a 17-year-old girl.","popularity":293.334,"poster_path":"/8xC6QSyxrpm0D5A6iyHNemEWBVe.jpg","release_date":"2020-11-12","title":"Freaky","video":false,"vote_average":6.8,"vote_count":340},
    
    {"adult":false,"backdrop_path":"/d1sVANghKKMZNvqjW0V6y1ejvV9.jpg","genre_ids":[16,28,12,14,18],"id":635302,"original_language":"ja","original_title":"劇場版「鬼滅の刃」無限列車編","overview":"Tanjirō Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyōjurō Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!","popularity":258.507,"poster_path":"/yF45egpHwaYLn4jTyZAgk0Cmug9.jpg","release_date":"2020-10-16","title":"Demon Slayer the Movie: Mugen Train","video":false,"vote_average":7.9,"vote_count":325},
    
    {"adult":false,"backdrop_path":"/e1zdlboXWPtOgY5TgeEEhYhJ098.jpg","genre_ids":[27,53],"id":728791,"original_language":"en","original_title":"Playhouse","overview":"Reckless Jack Travis is an irreverent horror writer notorious for scaring audiences. But as he obsesses over creating a new theatre show set in a haunted Scottish castle, demonic disturbances from deep within the walls begin to prey on his troubled daughter. When the alarming supernatural forces start to close in on him too, Jack is forced to reckon with the terrifying consequences of creating such a dark and macabre play. But will he realise the danger of unearthing a historic curse and stop writing before he damns himself, his personal sanity and those he loves forever?","popularity":220.1,"poster_path":"/1e6EJVJjRrhiU5BzK3LnzmbsMC0.jpg","release_date":"2021-01-28","title":"Playhouse","video":false,"vote_average":0,"vote_count":0},
    
    {"adult":false,"backdrop_path":"/z8TvnEVRenMSTemxYZwLGqFofgF.jpg","genre_ids":[14,28,12],"id":458576,"original_language":"en","original_title":"Monster Hunter","overview":"A portal transports Lt. Artemis and an elite unit of soldiers to a strange world where powerful monsters rule with deadly ferocity. Faced with relentless danger, the team encounters a mysterious hunter who may be their only hope to find a way home.","popularity":157.748,"poster_path":"/zO9R7Z6DRDgRO9QVz4lAJg3L15o.jpg","release_date":"2020-12-03","title":"Monster Hunter","video":false,"vote_average":5.5,"vote_count":57},
    
    {"adult":false,"backdrop_path":"/aQUM5qfBBdWQQk3mwKp6OLwv8mS.jpg","genre_ids":[16,28,18,878],"id":283566,"original_language":"ja","original_title":"シン・エヴァンゲリオン劇場版:||","overview":"The fourth and final film in the Rebuild of Evangelion series.","popularity":203.244,"poster_path":"/q034rbTWteRNA8sMSc2YjegmiUx.jpg","release_date":"2021-01-23","title":"Evangelion: 3.0+1.0 Thrice Upon a Time","video":false,"vote_average":0,"vote_count":0},
    
    {"adult":false,"backdrop_path":"/aSdp2uS0jWkqdhCeyhJuCoiLZji.jpg","genre_ids":[28,80,53],"id":603119,"original_language":"en","original_title":"The Silencing","overview":"A reformed hunter becomes involved in a deadly game of cat and mouse when he and the local sheriff set out to track a vicious killer who may have kidnapped his daughter years ago.","popularity":139.088,"poster_path":"/dnN1ncxEOO1TY0gYL2FWxJqlhlL.jpg","release_date":"2021-01-28","title":"The Silencing","video":false,"vote_average":0,"vote_count":0},
    
    {"adult":false,"backdrop_path":"/rWrvcsrvISKXdMOzCdkvU3Jtg0j.jpg","genre_ids":[53,80,18],"id":582014,"original_language":"en","original_title":"Promising Young Woman","overview":"A young woman haunted by a tragedy in her past takes revenge on the predatory men unlucky enough to cross her path.","popularity":97.91,"poster_path":"/73QoFJFmUrJfDG2EynFjNc5gJxk.jpg","release_date":"2020-12-13","title":"Promising Young Woman","video":false,"vote_average":7.4,"vote_count":69},
    
    {"adult":false,"backdrop_path":"/cSpwQ1BekQ6SL8JpUDmfsCBxJDz.jpg","genre_ids":[18,53,80],"id":596161,"original_language":"en","original_title":"Let Him Go","overview":"Following the loss of their son, a retired sheriff and his wife leave their Montana ranch to rescue their young grandson from the clutches of a dangerous family living off the grid in the Dakotas.","popularity":109.899,"poster_path":"/EsLZoT8oHhQlGd1QpdbnvnwTzO.jpg","release_date":"2020-11-05","title":"Let Him Go","video":false,"vote_average":7.3,"vote_count":123},
    
    {"adult":false,"backdrop_path":"/AdqOBPw4PdtzOcfEuQuZ8MNeTKb.jpg","genre_ids":[14,10751,12,18],"id":413518,"original_language":"it","original_title":"Pinocchio","overview":"In this live-action adaptation of the beloved fairytale, old woodcarver Geppetto fashions a wooden puppet, Pinocchio, who magically comes to life. Pinocchio longs for adventure and is easily led astray, encountering magical beasts, fantastical spectacles, while making friends and foes along his journey. However, his dream is to become a real boy, which can only come true if he finally changes his ways.","popularity":95.265,"poster_path":"/lzqJcPaZA9G8C6eS4Hch475Ng3A.jpg","release_date":"2019-12-19","title":"Pinocchio","video":false,"vote_average":6.7,"vote_count":868},
    
    {"adult":false,"backdrop_path":"/5TbtcmRySXPAEXBzwhiOYYDQmgv.jpg","genre_ids":[27,9648],"id":723072,"original_language":"en","original_title":"Host","overview":"Six friends hire a medium to hold a séance via Zoom during lockdown — but they get far more than they bargained for as things quickly go wrong. When an evil spirit starts invading their homes, they begin to realize they might not survive the night.","popularity":104.488,"poster_path":"/h7dZpJDORYs5c56dydbrLFkEXpE.jpg","release_date":"2020-12-04","title":"Host","video":false,"vote_average":7.2,"vote_count":60},
    
    {"adult":false,"backdrop_path":"/ugoims6PfRgcAcIgTRoK2uvjhOu.jpg","genre_ids":[18,37],"id":581032,"original_language":"en","original_title":"News of the World","overview":"A Texan traveling across the wild West bringing the news of the world to local townspeople, agrees to help rescue a young girl who was kidnapped.","popularity":110.251,"poster_path":"/fYQCgVRsQTEfUrP7cW5iAFVYOlh.jpg","release_date":"2020-12-25","title":"News of the World","video":false,"vote_average":7.5,"vote_count":46},
    
    {"adult":false,"backdrop_path":"/kJZI5tPWTVJrgmBCYMq8rkFP7Sk.jpg","genre_ids":[53,27],"id":720395,"original_language":"en","original_title":"Let It Snow","overview":"Separated from her fiance after sneaking onto a restricted slope, Mia, a free riding snowboarder, must survive not only against nature, but the masked snowmobile rider in black who's out for her blood.","popularity":83.183,"poster_path":"/rAeQaySpt5iSdK8eWOpBnSB8mGQ.jpg","release_date":"2021-01-28","title":"Let It Snow","video":false,"vote_average":0,"vote_count":0},
    
    {"adult":false,"backdrop_path":"/k99QNqdNdQMk9DAFswQpaDWht3B.jpg","genre_ids":[28,53,80],"id":634528,"original_language":"en","original_title":"The Marksman","overview":"A rancher on the Arizona border becomes the unlikely defender of a young Mexican boy desperately fleeing the cartel assassins who've pursued him into the U.S.","popularity":76.625,"poster_path":"/rVgegHud79yK18qDUq3Holb1C9T.jpg","release_date":"2021-01-15","title":"The Marksman","video":false,"vote_average":9.5,"vote_count":4}

];